add support for Raspberry Pi 4
WallaceIT/picberry pull request #17
Opened 2021-07-18 05:03 UTC by jake5253

Only tested on RPI4B 8GB version using default GPIO pins... but since the only thing really different is the peri_base address, if it worked on rpi1-3, everything should be golden on rpi4.

2021-07-18 05:14 UTC, jake5253 commented
pi@raspberrypi:~/picberry $ sudo picberry -f pic24fjxxxga0xx -d
picberry PIC Programmer v0.2
Device Name: PIC24FJ64GA002
Device ID: 0x00000447
Revision: 0x00003046

Configuration registers:

 - CW2: 0x00000ea0
 - CW1: 0x00000ea0

Press ENTER to exit program mode...
pi@raspberrypi:~/picberry $ sudo picberry -f pic24fjxxxga0xx -r out.hex
picberry PIC Programmer v0.2
Device Name: PIC24FJ64GA002
Device ID: 0x00000447
Revision: 0x00003046
Reading chip...DONE! 
Press ENTER to exit program mode...
pi@raspberrypi:~/picberry $ sudo picberry -f pic24fjxxxga0xx -b
picberry PIC Programmer v0.2
Device Name: PIC24FJ64GA002
Device ID: 0x00000447
Revision: 0x00003046
Blank check...chip is not blank.
Press ENTER to exit program mode...
pi@raspberrypi:~/picberry $ sudo picberry -f pic24fjxxxga0xx -e
picberry PIC Programmer v0.2
Device Name: PIC24FJ64GA002
Device ID: 0x00000447
Revision: 0x00003046
Bulk Erase...DONE!
Press ENTER to exit program mode...
pi@raspberrypi:~/picberry $ sudo picberry -f pic24fjxxxga0xx -b
picberry PIC Programmer v0.2
Device Name: PIC24FJ64GA002
Device ID: 0x00000447
Revision: 0x00003046
Blank check...chip is blank.
Press ENTER to exit program mode...
pi@raspberrypi:~/picberry $ sudo picberry -f pic24fjxxxga0xx -w BP_community_fw-v7.1.hex 
picberry PIC Programmer v0.2
Device Name: PIC24FJ64GA002
Device ID: 0x00000447
Revision: 0x00003046
Writing chip...[DONE! 
Press ENTER to exit program mode...
pi@raspberrypi:~/picberry $ 
pi@raspberrypi:~/picberry $ screen /dev/ttyUSB0 115200 8N1
Bus Pirate v3.5
Community Firmware v7.1 - goo.gl/gCzQnW [HiZ 1-WIRE UART I2C SPI 2WIRE 3WIRE KEYB LCD PIC DIO] Bootloader v255.255
DEVID:0x0447 REVID:0x3046 (24FJ64GA00 2 B8)
http://dangerousprototypes.com
HiZ>
`
Recovered my BusPirate woohoo!

2021-08-08 13:33 UTC, WallaceIT requested changes
Hello, thank you for your contribution! I only added a coupe of notes on naming scheme: since other RPi targets are in teh form _raspberrypiX_, I'd like to maintain this extended form.

Also, would you mind to add a line on support table on README?

Thank you!

2021-08-08 13:33 UTC, WallaceIT commented on Makefile
> +rpi4b: prepare picberry
See other comment on naming scheme

2021-08-08 13:33 UTC, WallaceIT commented on Makefile
> +rpi4b: CFLAGS += -DBOARD_RPI4B
I'd suggest _raspberrypi4b_ instead of _rpi4b_, to keep the same naming scheme as before

2023-01-10 21:23 UTC, WallaceIT commented
Hi @MikeDK,

as you can imagine, the project is not really maintained anymore... but if you open a MR I'll look injto it with pleasure!

2023-01-10 22:28 UTC, MikeDK commented
@WallaceIT already done that 😉

https://github.com/WallaceIT/picberry/pull/20

Too bad to hear its not maintained any more as this is a really cool project 👍

2023-01-10 22:49 UTC, WallaceIT commented
Functionality merged in #20 - closing this one.

Thanks to all who contributed!

2023-01-10 22:49 UTC, closed without merging